import React from 'react'
import styles from '@/styles/Courses.module.css';
import Navbar from '@/components/Navbar';
import Head from 'next/head';
import Course from '@/components/Course';

export default function courses() {
  return (
    <>
      <Head>
        <title>Coding Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles["main"]}>
        <Navbar></Navbar>
        <Course></Course>
      </main>
    </>
  )
}
